### PR TITLE
Async calculations

### PR DESCRIPTION
**Pull request by yarolegovich**
Aside from minor changes like moving from Stack to ArrayDeque or removing unnecessary Manifest tag, I added an option to calculate shadows asynchronously. 
I think most often developers can't afford to freeze the main thread.

### CODE REVIEW

**Comment by harjot-oberai** [comment]
That's some pretty neat stuff 😄 . Everything works perfectly 👍 .

**Comment by harjot-oberai** [comment]
The set method for `animationDuration` duration is missing. I believe its just an oversight but still just want to ask if you omitted it deliberately due to some reason ?

**Comment by yarolegovich** [comment]
That's just my oversight .

**Comment by harjot-oberai** [comment]
No worries, I will add it 👍 .

**Pull request merged**
